server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = / {
    return 302 /demo/;
  }

  location = /demo {
    return 302 /demo/;
  }

  location = /manage {
    return 302 /manage/;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
